# Generated by Django 4.0rc1 on 2021-11-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10, verbose_name='Nome')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('expected_allocation', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Alocação Esperada')),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
            },
        ),
    ]
