# Generated by Django 4.0.2 on 2022-03-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='company_name',
            field=models.CharField(default='', max_length=255, verbose_name='Nome da Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticker',
            name='document',
            field=models.CharField(default='', max_length=14, verbose_name='CNPJ da Empresa'),
            preserve_default=False,
        ),
    ]
