# Generated by Django 4.0rc1 on 2021-11-27 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ticket_remove_stockasset_name_stockasset_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='value',
            new_name='price',
        ),
    ]
