# Generated by Django 4.0rc1 on 2021-12-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_value_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Ação'), (1, 'FII'), (2, 'BDR'), (3, 'ETF')], default=0, verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
